name: Deploy in Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Build Docker images with the correct paths
    - run: docker build -t roshan602/blue-fox:03 ./frontend

    # Log in to Docker Hub
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Push Docker images to Docker Hub
    - run: docker push roshan602/blue-fox:03

    # Pull Docker images (optional, for verification)
    - run: docker pull roshan602/blue-fox:03

    # Run Docker containers
    - run: docker run -d --rm --name frontend -p 3000:3000 roshan602/blue-fox:03
